CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(16) NOT NULL,
    last_name VARCHAR(16) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    role VARCHAR(10) NOT NULL,
    image VARCHAR(512),
    password VARCHAR(64) NOT NULL
);

CREATE TABLE ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(32) NOT NULL,
    price INTEGER NOT NULL,
    description VARCHAR(64) NOT NULL,
    image VARCHAR(512),
    CONSTRAINT fk_ads_author_id FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    author_image VARCHAR(512),
    author_first_name VARCHAR(64),
    created_at BIGINT NOT NULL,
    text VARCHAR(64) NOT NULL,
    ad_id BIGINT NOT NULL,
    CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);
